// <auto-generated />
using System;
using BankingLedger.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BankingLedger.Infrastructure.Migrations
{
    [DbContext(typeof(BankingLedgerDbContext))]
    partial class BankingLedgerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BankingLedger.Domain.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("balance");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("owner_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("accounts", t =>
                        {
                            t.HasCheckConstraint("CK_accounts_balance_non_negative", "balance >= 0");
                            t.HasCheckConstraint("CK_accounts_owner_name_not_empty", "owner_name <> ''");
                            t.HasCheckConstraint("CK_accounts_status_valid", "status IN ('Active', 'Closed', 'Frozen')");
                        });
                });

            modelBuilder.Entity("BankingLedger.Domain.Ledger.LedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<decimal>("BalanceAfterTransaction")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("balance_after_transaction");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("description");

                    b.Property<Guid?>("TransferId")
                        .HasColumnType("uuid")
                        .HasColumnName("transfer_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "CreatedAtUtc")
                        .HasDatabaseName("IX_ledger_entries_account_id_created_at_utc");

                    b.ToTable("ledger_entries", t =>
                        {
                            t.HasCheckConstraint("CK_ledger_entries_amount_positive", "amount > 0");
                            t.HasCheckConstraint("CK_ledger_entries_type_valid", "type IN ('Deposit', 'Withdrawal', 'TransferDebit', 'TransferCredit')");
                        });
                });

            modelBuilder.Entity("BankingLedger.Domain.Transfers.Transfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<Guid>("FromAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_account_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("ToAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_account_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_transfers_created_at_utc");

                    b.HasIndex("FromAccountId")
                        .HasDatabaseName("IX_transfers_from_account_id");

                    b.HasIndex("ToAccountId")
                        .HasDatabaseName("IX_transfers_to_account_id");

                    b.ToTable("transfers", t =>
                        {
                            t.HasCheckConstraint("CK_transfers_amount_positive", "amount > 0");
                            t.HasCheckConstraint("CK_transfers_different_accounts", "from_account_id <> to_account_id");
                            t.HasCheckConstraint("CK_transfers_status_valid", "status IN ('Pending', 'Completed', 'Failed', 'RolledBack')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
